### ISSUE TITLE
travis_retry: command not found when running prerelease_test.sh

### ISSUE THREAD

**Issue by ykoga-kyutech** [seqsense/urg_stamped#76]
After [the change](https://github.com/seqsense/urg_stamped/pull/69/files#diff-783e4aa9cfa240aa185ff15768233143R27), `travis_retry` is used in prerelease_test.sh shell script, but it shows the following error.
`.travis/prerelease_test.sh: line 27: travis_retry: command not found`.
https://travis-ci.com/github/seqsense/urg_stamped/jobs/370588033

Travis says this is because "it’s a shell function, so it’s not available in subshells/commands" https://twitter.com/travisci/status/499195739353153539
We can solve it by removing the command or creating a new file by copy-and-paste.

**Comment by f-fl0** [comment]
The twitter comment suggests an implementation of the `travis_retry` function and to copy it directly.  Should we add https://github.com/travis-ci/travis-build/blob/73f74a94957f73eb54dc821f80c0c85ad8f8aab7/lib/travis/build/script/templates/header.sh#L168-L187 to `.travis/prerelease_test.sh`?

**Comment by at-wat** [comment]
`apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key` often fails.

```diff
- travis_retry sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
+ recv_key='sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654'
+ ${recv_key} || ${recv_key} || ${recv_key}
```
would be enough.
